### ISSUE TITLE
Why you didn't exclude .tsx or .ts files from eslinter?

### ISSUE THREAD

**Issue by rzkhosroshahi** [Can-Sahin/react-boilerplate-typescript#10] opened 2019-01-23 12:06 UTC
Hi,
I can't figure out that why you should using eslinter for typescript files, even though you installed tslint for these type files?

**Comment by Can-Sahin** [comment] 2019-01-23 16:03
Hi, I didn't understand much. `.eslintrc.js` don't have any tsx definitions. I simply didn't touch js related files at all. Since, people can still write js code and when the new versions are released I would have less problems merging from the orijinal boilerplate

**Comment by rzkhosroshahi** [comment] 2019-01-24 21:57
> Hi, I didn't understand much. `.eslintrc.js` don't have any tsx definitions. I simply didn't touch js related files at all. Since, people can still write js code and when the new versions are released I would have less problems merging from the orijinal boilerplate

![screen shot 2019-01-25 at 1 13 09 am](https://user-images.githubusercontent.com/11410506/51710664-1d699d00-203f-11e9-926b-e2d3b9a95007.png)
 Look this image I got lint error from eslint in `ts` file. you're correct `tsx` files don't definition from eslint but as you can see it seems still `ts` files definitions from it.

**Comment by Can-Sahin** [comment] 2019-01-25 15:36
Hmmm. I absolutely have no idea why and I cannot reproduce this. I used this boilerplate in three different projects (cloning from master) and had no such issue. Maybe you have some generic eslint settings somewhere or something similar?

**Comment by Can-Sahin** [comment] 2019-01-25 20:44
closing since #11 is merged

**Closed as completed by Can-Sahin** 2019-01-25 20:44 UTC
